### ISSUE TITLE
Command step " ./build-gnuradio -v" failed

### ISSUE THREAD

**Issue by dominicantonyv** [mgp25/OpenLTE#1]
Hi

When I ran the command ` ./build-gnuradio -v` to install GNU Radio with UHD as per the instructions given in [Readme](https://github.com/mgp25/OpenLTE/blob/master/README.md), I got the following error and the build/install failed.

`/home/MySytemName/gnuradio/gnuradio/gr-fec/lib/polar_decoder_common.cc: In member function ‘void gr::fec::code::polar_decoder_common::butterfly_volk(float*, unsigned char*, int, int, int)’:
/home/MySystemName/gnuradio/gnuradio/gr-fec/lib/polar_decoder_common.cc:128:95: error: too many arguments to function
         volk_32f_8u_polarbutterfly_32f(llrs, u, block_size(), block_power(), stage, u_num, row);
                                                                                               ^
make[2]: *** [gr-fec/lib/CMakeFiles/gnuradio-fec.dir/polar_decoder_common.cc.o] Error 1
make[1]: *** [gr-fec/lib/CMakeFiles/gnuradio-fec.dir/all] Error 2
make: *** [all] Error 2
make failed
Exiting Gnu Radio build/install`

Someone please help. Has anyone succeeded in building & installing and running this OpenLTE project. Thanks

**Comment by mgp25** [comment]
Hello @dominicantonyv,

Yes, we were able to install OpenLTE successfully. Well your issue is not related to OpenLTE but one of its dependencies, `GNU Radio`.

You can follow this guide: [Installing GNU Radio](https://wiki.gnuradio.org/index.php/InstallingGR)

After `GNU Radio` is installed correctly, you can continue with the [Readme](https://github.com/mgp25/OpenLTE/blob/master/README.md) guide.

Regards
